version: '2'
services:
    openresty:
      restart: always
      image: openresty/openresty:trusty
      dns:
        - 8.8.8.8
      ports:
        - "80:80"
        - "443:443" #todo tls support
      privileged: true
      volumes:
        - ./lua/:/usr/local/openresty/nginx/conf/lua
        - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

